/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Modelo.ArchivoEntrada;
import Modelo.ArchivoSalida;
import Modelo.EstudianteDatos;
import Modelo.tbCalificaciones;
import java.io.File;

import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Lenovo
 */
public class JFModificar extends javax.swing.JFrame {
   public tbCalificaciones modelo = new tbCalificaciones();
   tbCalificaciones entrada = new tbCalificaciones();
   List<EstudianteDatos> estudiantesList = entrada.readFile();
    /**
     * Creates new form JFModificar
     */
   
    public JFModificar() {
       
        initComponents();
        modelo.inicializaTabla(tblCal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCal = new javax.swing.JTable();
        btmImprimirPDF = new javax.swing.JButton();
        btmModificar = new javax.swing.JButton();
        btmRegresar = new javax.swing.JButton();
        lbMatricula1 = new javax.swing.JLabel();
        txtCalifNueva = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        lbMatricula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        lblTitle.setText("Modificar calificaciones");

        tblCal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCal);

        btmImprimirPDF.setText("Imprimir PDF");
        btmImprimirPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmImprimirPDFActionPerformed(evt);
            }
        });

        btmModificar.setText("Modificar");
        btmModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmModificarMouseClicked(evt);
            }
        });

        btmRegresar.setText("Regresar");
        btmRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRegresarActionPerformed(evt);
            }
        });

        lbMatricula1.setText("Calificación nueva:");

        lbMatricula.setText("Matrícula: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btmRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btmModificar)
                        .addGap(77, 77, 77)
                        .addComponent(btmImprimirPDF)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(137, 137, 137))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(lbMatricula1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCalifNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalifNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMatricula1)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmImprimirPDF)
                    .addComponent(btmModificar)
                    .addComponent(btmRegresar))
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmImprimirPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmImprimirPDFActionPerformed
        ArchivoEntrada entrada2 = new ArchivoEntrada();
        List<EstudianteDatos> estudiantesLista = entrada2.readFile();
        ArchivoSalida salida = new ArchivoSalida();
       
        for (int i = 0; i < estudiantesLista.size(); i++){
           estudiantesLista.get(i).setCalificacion(estudiantesList.get(i).getCalificacion());
        }
        salida.crearPDF(estudiantesLista);
        JOptionPane.showMessageDialog(null, "PDF generado.");
    }//GEN-LAST:event_btmImprimirPDFActionPerformed

    private void btmModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmModificarMouseClicked
       
        try{
        int matricula = Integer.valueOf(this.txtMatricula.getText());
        int califNueva = Integer.valueOf(this.txtCalifNueva.getText());
      
        for (int i = 0; i < estudiantesList.size(); i++){
            if (estudiantesList.get(i).getMatricula() == matricula ){
                estudiantesList.get(i).setCalificacion(califNueva);
                //JOptionPane.showMessageDialog(null, matricula +" "+ String.valueOf(estudiantesList.get(i).getMatricula()) +" "+ estudiantesList.get(i).getCalificacion());
                modelo.setValue(tblCal, estudiantesList);
            }
        }
        File file = new File("calificaciones.csv");
        file.delete();
        ArchivoSalida salida = new ArchivoSalida();
        salida.createFile(estudiantesList);
        JOptionPane.showMessageDialog(null, "Calificaciones guardadas.");
        
        } catch (NumberFormatException e1) {
            JOptionPane.showMessageDialog(null, "Error: Inserte valores numéricos.");
        } catch (IndexOutOfBoundsException e2){
            JOptionPane.showMessageDialog(null, "Error: No hay más estudiantes.");
        }
    }//GEN-LAST:event_btmModificarMouseClicked

    private void btmRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRegresarActionPerformed
        this.dispose();
        JFInicio inicio = new JFInicio();
        inicio.setVisible(true);
    }//GEN-LAST:event_btmRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmImprimirPDF;
    private javax.swing.JButton btmModificar;
    private javax.swing.JButton btmRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbMatricula1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCal;
    private javax.swing.JTextField txtCalifNueva;
    private javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables
}
